name: Deploy_storybook

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          npm install
      - name: Deploy
        run: |
          npm run deploy-storybook
